console.log("hai")
console.log("helllllllll")
console.log("welcoe s")
console.log("helloppp")
console.log("hai")
console.log("welocme")
console.log("haidd")
console.log("arun")
console.log("hello eery one ")
console.log("heloddd")