console.log("hai")
console.log("helllllllll")
console.log("welcoe s")
console.log("helloppp")
console.log("hai")
console.log("fffffffffffffffffffff")
console.log("welocme")
console.log("haidd")
console.log("main")
console.log("arun")
console.log("hello eery one ")
console.log("heloddd")
console.log("hai")
console.log("am")
console.log("mega stat")
